
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 20 03:49:03 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RETROCEDER = 19;
  public static final int PARAR = 9;
  public static final int SENSOR = 24;
  public static final int IZQUIERDA = 10;
  public static final int CERRAR = 35;
  public static final int VERDADERO = 15;
  public static final int MAYOR = 57;
  public static final int NORESTE = 47;
  public static final int SUR = 44;
  public static final int DIGITAL = 21;
  public static final int INICIO = 7;
  public static final int ESTE = 45;
  public static final int SURESTE = 49;
  public static final int EVALUAR = 42;
  public static final int SUBIR = 34;
  public static final int FALSO = 16;
  public static final int Resta = 68;
  public static final int UNO = 74;
  public static final int FUNCION = 63;
  public static final int NumeroEnt = 76;
  public static final int NOT = 60;
  public static final int Suma = 67;
  public static final int DELANTERA = 29;
  public static final int OESTE = 46;
  public static final int ERROR = 5;
  public static final int ERRORP = 73;
  public static final int LUZ = 23;
  public static final int NOROESTE = 48;
  public static final int RUEDAS = 32;
  public static final int CICLO = 13;
  public static final int OPCION = 41;
  public static final int ENTERO = 20;
  public static final int ERROR2 = 72;
  public static final int ERROR1 = 71;
  public static final int Asignacion = 66;
  public static final int CONDICION = 17;
  public static final int DIFERENTEDE = 53;
  public static final int FIN = 8;
  public static final int FINLI = 6;
  public static final int MENOR = 56;
  public static final int BANDERA = 14;
  public static final int CORCHI = 61;
  public static final int ABRIR = 36;
  public static final int PROXIMIDAD = 27;
  public static final int CORCHD = 64;
  public static final int EOF = 0;
  public static final int Numero = 4;
  public static final int Division = 70;
  public static final int SUROESTE = 50;
  public static final int MENORIGUAL = 55;
  public static final int CABINA = 31;
  public static final int GANCHO = 37;
  public static final int IGUALQUE = 52;
  public static final int PRINCIPAL = 2;
  public static final int COMILLA = 77;
  public static final int ROMPER = 39;
  public static final int OR = 58;
  public static final int error = 1;
  public static final int AVANZAR = 18;
  public static final int ENTRADA = 25;
  public static final int NORTE = 43;
  public static final int PARENTESISI = 62;
  public static final int DERECHA = 11;
  public static final int PARENTESISD = 65;
  public static final int Identificador = 3;
  public static final int CERO = 75;
  public static final int NINGUNO = 51;
  public static final int MAYORIGUAL = 54;
  public static final int ESTADO = 28;
  public static final int BOCINA = 38;
  public static final int AND = 59;
  public static final int ANALOGO = 22;
  public static final int BAJAR = 33;
  public static final int TRASERA = 30;
  public static final int GIRAR = 12;
  public static final int Multiplicacion = 69;
  public static final int SALIDA = 26;
  public static final int REPETIR = 40;
}

